### ISSUE TITLE
Travis CI and Enzyme

### ISSUE THREAD

**Issue by yh2n** [yh2n/central#7]
The tests that pass locally fail on Travis. The problem comes from an issue with Enzyme:
"Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
          To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:
          import Adapter from 'enzyme-adapter-react-15'; "

**Comment by yh2n** [comment]
When I import the setupTests.js file to each testes files I get the following message:
FAIL  src/tests/UserAccount.test.js
  ● Test suite failed to run
    Cannot find module '../../src/setupTests' from 'UserAccount.test.js'
      
      at Resolver.resolveModule (node_modules/react-scripts/node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/tests/UserAccount.test.js:3:1)

**Comment by yh2n** [comment]
The issue probably comes the fact that cient and API are on the same repo with each them having their own package.json files.
